### ISSUE TITLE
[BUG] NPC interact/dialog instant close

### ISSUE THREAD

**Issue by kompolompo** [balakethelock/SuperWoW#42]
**Describe the bug**
When using super wow with turtle wow with any hardcore chars any NPC dialog just instant close, transmog, sellers, trainers. Normal chars just work.

**To Reproduce**
1. normal chars just works all addons off or on
2. hc chars bugg is back all addons on or off.
3. skip the superwow launcher exe it just works again

**Expected behavior**
To be able to sell or transmog or just read any npc dialog and take your time to choose dialog.

**Screenshots**
Does not matter I guess since dialog instant closes. Would just be a picture of a NPC

**Additional context**
Add any other context about the problem here: Server where the bug happened, other mods in use.

**Comment by EzioAu** [comment]
it happens to my hc paladin as well but my hc mage has no issue at all , its weird.

**Comment by tthe3d** [comment]
I can confirm , this is a big problem. You can trick it by opening the dialogue shop option really fast , but sometimes the window closes too fast and you got no time to click the dialogue. And its basically a racing game every singe time you wanna talk to some NPC. I find that holding shift helps sometimes, but right now , I am forced to use the official launcher when I'm just doing quests and use the Superwow launcher when doing dungeons , because of the obvious benefits. This issue happens in hardcore only as far as I know.

**Comment by Hollandex** [comment]
Also experiencing this. Please make it stop. :(

**Comment by mzynn** [comment]
having this issue pls fix.

**Comment by mzynn** [comment]
Is there a fix for this issue yet? it keeps coming back. I thought it fixed with the latest version but it just started happening again on my hc mage questing in redridge. i changed the fov via superapi and noticed thats when it started happening. Please find a fix.

**Comment by balakethelock** [comment]
Has any of you tried asking twow devs why it happens to only hard cores? Surely it's something server side don't you think?

**Comment by Nerenye** [comment]
is this still maintained? Still persists

**Comment by Ge3e** [comment]
Yes it's still happening to me. I'm a HC player. If I talk to any NPC eg Flight,  bank etc the window closes quickly.  I have to reopen it.

**Comment by Xian55** [comment]
Gooday, i have a 100% repro of this in Turtle wow.

Speak with Felicia in Stormwind. She's a custom NPC.
<img width="385" height="346" alt="Image" src="https://github.com/user-attachments/assets/d1f28bd7-ee0d-4e83-9e1d-a4de83d25751" />

While SuperWoW is active, after interacting with her, after around 3-4 seconds the window closes automatically.

Repro of the case
https://github.com/user-attachments/assets/45ad7985-3f2f-42f2-a9b7-735ccd9a6f9d
